sudo: required
dist: trusty
language: bash

services:
- docker

env: 
  - ARCH=amd64
  - ARCH=i386

install:
  - sh ./build_environment.sh

script:
  - sh ./build_dockerfile.sh
  - travis_wait 60 docker build --compress --squash -t "${REPO}:${ARCH}-${TAG}" -f Dockerfile."${ARCH}" .
  - docker images "${REPO}:${ARCH}-${TAG}"
  - docker run --entrypoint "uname" -t "${REPO}:${ARCH}-${TAG}" -a
  - sh ./deploy_container.sh

jobs:
  include:
    - stage: deploy manifest
      env:
        - PUBTAG=${TRAVIS_BUILD_NUMBER}
        - ARCH=amd64 i386
      script: bash ./deploy_manifest.sh
    - stage: deploy manifest latest
      if: branch = master
      env:
        - PUBTAG=latest
        - ARCH=amd64 i386
      script: bash ./deploy_manifest.sh